apiVersion: v1
kind: Pod
metadata:
  name: training-job-a
  labels:
    runai/queue: project-c
spec:
  schedulerName: kai-scheduler
  containers:
  - name: training
    image: gcr.io/run-ai-demo/quickstart-demo
    resources:
      requests:
        nvidia.com/gpu: "4"
      limits:
        nvidia.com/gpu: "4"
---
apiVersion: v1
kind: Pod
metadata:
  name: training-job-b
  labels:
    runai/queue: project-a
spec:
  schedulerName: kai-scheduler
  containers:
  - name: training
    image: gcr.io/run-ai-demo/quickstart-demo
    resources:
      requests:
        nvidia.com/gpu: "1"
      limits:
        nvidia.com/gpu: "1"
