apiVersion: v1
kind: Pod
metadata:
  name: training-job-a
  labels:
    runai/queue: project-c
spec:
  schedulerName: kai-scheduler
  containers:
  - name: training
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    resources:
      requests:
        nvidia.com/gpu: "4"
      limits:
        nvidia.com/gpu: "4"
    command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: training-job-b
  labels:
    runai/queue: project-a
spec:
  schedulerName: kai-scheduler
  containers:
  - name: training
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    resources:
      requests:
        nvidia.com/gpu: "3"
      limits:
        nvidia.com/gpu: "3"
    command: ["sleep", "3600"] 
